### PR TITLE
Fix/add more a11y to map

### PR DESCRIPTION
**Pull request by nickvisut**
For map marker, add the following for keyboard nav/a11y:
- Trigger popup on focus
- Add focus styling by copying active styling
- Replace outline effect with something closer to our design

Also addresses #210 so that focused marker comes to foreground.

### CODE REVIEW

**Comment by nickvisut** [comment]
I may separate out the tweaked outline depending on feedback and leave only the first two bullet points

**Comment by nickvisut** [comment]
> I may separate out the tweaked outline depending on feedback and leave only the first two bullet points

It's been given the thumbs-up, so this PR is ready to go, although we'll want to address any potential a11y contrast issues.

**Comment by nickvisut** [comment]
Pushed missing commit that addresses #210

**Review by BeeSeeWhy — APPROVED** [review]
This looks great.

**Pull request merged**
