### PR TITLE
[Closes #34] Feature: Back to top button

### LINKED ISSUE #34: button to go back to top
- for mobile only: need a button at bottom to go back up to the top on the profile page
- (see Figma for design)

### PR DESCRIPTION
**Pull request by javtran**
Addresses #34

Back to top button appears when scroll action happens. 
Scrolls back to the top.

### CODE REVIEW

**Comment by mattgianni** [comment]
Works smoothly. Nice!

It does seem to obscure the arrow icon on the school card images though. Do you think it'd look strange to move it left a little to avoid the overlap?

chrome_0aPXhPoBPb

**Comment by javtran** [comment]
> Works smoothly. Nice!
> 
> It does seem to obscure the arrow icon on the school card images though. Do you think it'd look strange to move it left a little to avoid the overlap?
> 
> chrome_0aPXhPoBPb

Thanks for pointing that out! Let me see what the designers say about this. @juliagoolia

**Comment by juliagoolia** [comment]
per 8/14 discussion let's add some buffer below the list - ~1.5x the size of the icon- so that the "back to top" button is just lower down

**Comment by nickvisut** [comment]
> per 8/14 discussion let's add some buffer below the list - ~1.5x the size of the icon (50x50)- so that the "back to top" button is just lower down

FYI this is what 75px on the 50x50 button* looks like:
Screenshot 2024-08-16 at 1 16 12 PM

cc @juliagoolia @javtran

*3.75rem on the 2.5rem by 2.5rem button

**Comment by nickvisut** [comment]
> 75px
> 3.75rem

some alternatives to the screenshot above:

- **3.5rem**
Screenshot 2024-08-16 at 1 48 42 PM

**- 4rem**
Screenshot 2024-08-16 at 1 50 06 PM

- 4.5rem
Screenshot 2024-08-16 at 1 50 18 PM

**- 5rem**
Screenshot 2024-08-16 at 1 50 33 PM

4.5rem looks the best to my eyes, but the bolded options (3.5, 4, 4.5) are slightly more preferable b/c they conform to Tailwind defaults and don't require a one-off CSS rule.

**Comment by javtran** [comment]
> per 8/14 discussion let's add some buffer below the list - ~1.5x the size of the icon (50x50)- so that the "back to top" button is just lower down

@juliagoolia @nickvisut 

Hmm... I feel like making a space specifically for the back to top button feels a little wasteful. I was looking up what other apps/websites do with this. They move the back to top button to the middle and/or play around with the opacity, so users can see through them. Let me know how this feels. 

https://github.com/user-attachments/assets/f2480b20-c907-48ec-a65b-8bec54d438df

**Comment by juliagoolia** [comment]
@nickvisut thanks for the options and @javtran thanks for the alt version- that makes sense to me too

**Comment by nickvisut** [comment]
> > per 8/14 discussion let's add some buffer below the list - ~1.5x the size of the icon (50x50)- so that the "back to top" button is just lower down
> 
> @juliagoolia @nickvisut
> 
> Hmm... I feel like making a space specifically for the back to top button feels a little wasteful. I was looking up what other apps/websites do with this. They move the back to top button to the middle and/or play around with the opacity, so users can see through them. Let me know how this feels.
> 
>  Recording.2024-08-20.123741.mp4

great point and looks like an elegant solution to me!

**Review by nickvisut — APPROVED** [review]
lgtm, works well

**Pull request merged**
