### PR TITLE
[Closes #36] added mapbox geolocation feature

### LINKED ISSUE #36: investigate geo-locating user from browser
- enabling the location from the browser would allow the map to geo locate and (ideally) pick the closest school
- https://docs.mapbox.com/mapbox-gl-js/example/locate-user/

### PR DESCRIPTION
**Pull request by rooiss**
- mapbox has a geolocation feature that I added to our map

### CODE REVIEW

**Comment by rooiss** [comment]
Putting this back into a draft, the geolocation works if you are within the `maxBounds` which most if not all of our user base will be within. Testing outside of the bounds will throw an error so have to discuss what the error handling should be and implement that.

**Comment by rooiss** [comment]
after feedback, I changed the implementation of how this works
- if a user is out of bounds the map will just remove the icon to geolocate
  - feels a little clunky since the user is asked to allow the location and then the geolocate icon disappears
 - I tried a variety of different implementations but this seemed to make the most sense
 - I'm definitely open to any suggestions, and wouldn't mind implementing an out of bounds message but that would require a design as well

**Review by BeeSeeWhy — CHANGES_REQUESTED** [review]
Geolocation works well. I was wondering if there is a reason the schools don't appear on the map though

**Comment by rooiss** [comment]
> Geolocation works well. I was wondering if there is a reason the schools don't appear on the map though

@BeeSeeWhy im looking at the vercel deployment and see the schools on the map, can you screen shot the issue?

**Comment by BeeSeeWhy** [comment]
Hmm...this might be somehow a me issue since this is on main 
Screenshot 2024-04-03 at 5 13 59 PM

**Review by BeeSeeWhy — APPROVED** [review]

**Pull request merged**
