### PR TITLE
Feature/create map list view

### LINKED ISSUE #17: Create Map List View Component [Eng]

### PR DESCRIPTION
**Pull request by karlystark**
Create Map List View Component [Eng]  
Fixes #17

- Created a simple MapList component that displays a series of MapListCard components. 
- The school card design rendered in MapListCard matches the expanded list card design found in Figma (we will need to implement the expandable card feature in a future issue, I'll add to issue list).

### CODE REVIEW

**Comment by rooiss** [comment]
@karlystark 
- Looks like the build failed from removing the state being passed into the `MapList` component and not being updated in the `pages/map` file
image
- I originally wanted to pass the event handler `setSelectedSchool` into the `MapList` so that when it was clicked, the `map` page would know which school was selected. Both `MapList` and `MapboxMap` share `setSelectedSchool`. I'm definitely open to suggestions so let me know what you were thinking


- also I would suggest updating the text for the list view since the marker only pertains to the map
image

**Review by rooiss — CHANGES_REQUESTED** [review]
I added some comments in the PR to fix the vercel deployment issue

**Comment by karlystark** [comment]
thank you @roois - I got setSelectedSchool back in there, sorry for that design oversight! I agree re: the text. It's set up in the map.tsx currently, but I went in there quickly and updated it. Let me know if you see anything else, and thank you!

**Comment by rooiss** [comment]
@karlystark noooice, looks great!

**Review by rooiss — APPROVED** [review]
looks great!

**Pull request merged**
