### PR TITLE
[CLOSES #50] added school name and color change to hover on map pin  

### LINKED ISSUE #50: Desktop: MapView : add hover over pin on map to reveal school name
Add Hover on pins to reveal school name 
Remove  reveal school name on map when clicked

### PR DESCRIPTION
**Pull request by mvyenielo**
The school name appears and the pin color now changes when moused over.

I found `"marker_hover.svg"` in our public folder and used that image, as otherwise I could not find a way to change the color of the marker, but I don't know if we're ok with that color. 

I figured I'd submit for now, and we can investigate changing it to a different color if necessary.

(see video preview below)

https://github.com/sfbrigade/support-sfusd/assets/139294550/6eda8cf5-c7fb-497f-9170-071231d2ebb2

### CODE REVIEW

**Comment by rooiss** [comment]
@mvyenielo I'm looking at the selected highlight and it seems to bleed over the outline on the right side. My best guess is that the selected marker is the exact same svg in a different color but offset to the right, or that the svg could actually just fit inside the outlined marker but off center. Assuming we'll change the color later on, could the marker be set to the same position so it just entirely overlaps the other marker (So that way the selected marker regardless of color can be centered)

image
image

**Review by rooiss — CHANGES_REQUESTED** [review]
@mvyenielo I'm looking at the selected highlight and it seems to bleed over the outline on the right side. My best guess is that the selected marker is the exact same svg in a different color but offset to the right, or that the svg could actually just fit inside the outlined marker but off center. Assuming we'll change the color later on, could the marker be set to the same position so it just entirely overlaps the other marker (So that way the selected marker regardless of color can be centered)

image
image

**Comment by mvyenielo** [comment]
Thank you! I think it should be fixed now. The hover pin is no longer bleeding over and I updated the pin color.
Screenshot 2024-04-25 at 9 11 30 AM

**Review by rooiss — APPROVED** [review]
@mvyenielo Sweeet nice work!!

**Pull request merged**
