### PR TITLE
add close button for beta banner

### PR DESCRIPTION
**Pull request by nickvisut**
temporarily adds close icon from map school card to beta banner

NOTE: temporary solution until design does a treatment

### CODE REVIEW

**Review by BeeSeeWhy — CHANGES_REQUESTED** [review]
It looks good...it shows up on map. Are we just doing profiles or map/list as well?

**Comment by nickvisut** [comment]
> It looks good...it shows up on map. Are we just doing profiles or map/list as well?

the fix for where it shows up was in the other branch and should be in main now; let me merge it!

**Comment by nickvisut** [comment]
OK, I borked merge conflict resolution but just fixed it. Also added a bit of margin to left of close icon

**Comment by nickvisut** [comment]
Preview looks good and only shows up on school profile page. Please test dismissal, which will dismiss banner only until next page reload.

**Review by BeeSeeWhy — APPROVED** [review]
looks good

**Pull request merged**
