### PR TITLE
Feature/prisma school profile model

### PR DESCRIPTION
**Pull request by mvyenielo**
- Added SchoolProfile, Program, and Metric models to Prisma schema
- Updated seed file to populate all June Jordan info
- Questionable items: 
    - How do we deal with hyperlinks within the "about" section or in the description of some programs? For now I left them out. I also left out "Learn more here!" from the text in some programs as it included hyperlinks. 
    - The "category" field for Programs and Metrics could potentially be an enum
    - Singular vs. plural model names?

### CODE REVIEW

**Review by BeeSeeWhy — APPROVED** [review]
I think this looks great

**Review by rooiss — CHANGES_REQUESTED** [review]
Nice! My only suggestion here would be to change the `category` of `Metric` and `Program` to be an `enum`

**Comment by mvyenielo** [comment]
@rooiss @BeeSeeWhy 
- I changed category for `Metric` and `Program` to an `enum`, the options are definitely subject to change:
    - for `Metric`, the current options are: `demographic`, `outcome`
    - for `Program`, the current options are: `volunteer`, `donate`, `enrichment`, `donation_funded`, `donors_choose`
- I changed `Schools` model to `School`

**Review by rooiss — APPROVED** [review]
Looks great! ~~I'm gonna go ahead and merge this in so I can resolve the build error~~

**Pull request merged**
