### PR TITLE
6 change toggle from icons to words eng

### PR DESCRIPTION
**Pull request by karlystark**
- Created ToggleButton component and updated styling to include text and icon. 
- ToggleButton component is rendered within MapView. 
- Communicated with Jesse to get the most recent toggle design.
- Added svgs for the current map/list icons. 
- Incorporated aria and focus in ToggleButton to ensure that the button is read as a switch/toggle and is navigable for those using screen readers.

### CODE REVIEW

**Comment by BeeSeeWhy** [comment]
Code looks good. If you resolve the branch conflicts, then we should be able to merge with main

**Review by BeeSeeWhy — COMMENTED** [review]
Code looks good. Just fix the merge conflicts and we should be able to squash and merge

**Comment by karlystark** [comment]
awesome, thank you!! I'll have a quick meeting w Hamilton this week to chat about how to integrate the toggle into the new map component and resolve the conflicts.

**Comment by karlystark** [comment]
Hi Brandon, I've met with Hamilton and discussed the merge conflicts and we'll add some tickets to continue work on the MapView and List components. Thank you!

**Pull request merged**
