### PR TITLE
fix templates for two issue types

### PR DESCRIPTION
**Pull request by nickvisut**
feature and other issue template were broken due to unallowed empty string value

### CODE REVIEW

**Comment by mattgianni** [comment]
I'm super new to GitHub issue templates, so hopefully I'm not leading you astray, but GitHub is still complaining about other.yml. It claims the [title](https://github.com/sfbrigade/support-sfusd/blob/bca473327f0c73bdf02cbff7868b322d1f3905d4/.github/ISSUE_TEMPLATE/other.yml#L4C1-L4C10) needs to be populated. 

The error states: `title must be of type String and cannot be empty.`

Probably just need to put something like "[Other]:" in there.

**Comment by mattgianni** [comment]
Also, maybe it's time to retire the lingering, legacy template, [ISSUE_TEMPLATE.md](https://github.com/sfbrigade/support-sfusd/blob/develop/ISSUE_TEMPLATE.md). It's just hanging out in the project root currently. (It's deprecated, ya?)

**Comment by nickvisut** [comment]
> I'm super new to GitHub issue templates, so hopefully I'm not leading you astray, but GitHub is still complaining about other.yml. It claims the [title](https://github.com/sfbrigade/support-sfusd/blob/bca473327f0c73bdf02cbff7868b322d1f3905d4/.github/ISSUE_TEMPLATE/other.yml#L4C1-L4C10) needs to be populated.
> 
> The error states: `title must be of type String and cannot be empty.`
> 
> Probably just need to put something like "[Other]:" in there.

Not leading me astray at all. Thank you and fixed. Did you go directly to https://github.com/sfbrigade/support-sfusd/blob/fix/issue-templates/.github/ISSUE_TEMPLATE/other.yml to see the error message? Could not find a way to validate it elsewhere.

**Comment by nickvisut** [comment]
> Also, maybe it's time to retire the lingering, legacy template, [ISSUE_TEMPLATE.md](https://github.com/sfbrigade/support-sfusd/blob/develop/ISSUE_TEMPLATE.md). It's just hanging out in the project root currently. (It's deprecated, ya?)
> 
> The `feature` template looks great and works perfectly IMO.

agreed, will drop this after the feature/other get some usage

**Comment by nickvisut** [comment]
This is ready for review again, @mattgianni @BeeSeeWhy

**Comment by mattgianni** [comment]
> > I'm super new to GitHub issue templates, so hopefully I'm not leading you astray, but GitHub is still complaining about other.yml. It claims the [title](https://github.com/sfbrigade/support-sfusd/blob/bca473327f0c73bdf02cbff7868b322d1f3905d4/.github/ISSUE_TEMPLATE/other.yml#L4C1-L4C10) needs to be populated.
> > The error states: `title must be of type String and cannot be empty.`
> > Probably just need to put something like "[Other]:" in there.
> 
> Not leading me astray at all. Thank you and fixed. Did you go directly to https://github.com/sfbrigade/support-sfusd/blob/fix/issue-templates/.github/ISSUE_TEMPLATE/other.yml to see the error message? Could not find a way to validate it elsewhere.

I ended up forking the repo and made this branch my primary to test. There is probably an easier way, but like I said, I'm super new to the templates. :)

**Comment by mattgianni** [comment]
After following my previous process (forking the repo, merge, test) - everything looks good from a functionality perspective (I think). Everything looks like it's working to me!

However, I'm using [VS Code](https://code.visualstudio.com/) and I installed an extension for [YAML support from RedHat (redhat.vscode-yaml)](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml). This utility pulls YAML scheme details for a very wide variety of file formats, including GitHub Issue templates and configuration.

This extension is offering a couple suggested fixes (though as I said, I think the templates are working anyway ... so maybe not worth worrying too much about):

`config.yml`

- Missing property "name"
- Missing property "description"
- Missing property "body"
- Property blank_issues_enabled is not allowed
- Property contact_links is not allowed

`other.yml`

- String is shorter than the minimum length of 1 (referencing the empty string in the property `labels`)

If you want to try to "fix" these warning, feel free ... but like I said, everything seems to be working to me!

**Review by mattgianni — APPROVED** [review]
As I mentioned in a previous comment, the RedHat YAML validator is still complaining a little, but everything looks great from a UX perspective. Happy to approve as-is, or review another revision.

**Comment by nickvisut** [comment]
> After following my previous process (forking the repo, merge, test) - everything looks good from a functionality perspective (I think). Everything looks like it's working to me!
> 
> However, I'm using [VS Code](https://code.visualstudio.com/) and I installed an extension for [YAML support from RedHat (redhat.vscode-yaml)](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml). This utility pulls YAML scheme details for a very wide variety of file formats, including GitHub Issue templates and configuration.
> 
> This extension is offering a couple suggested fixes (though as I said, I think the templates are working anyway ... so maybe not worth worrying too much about):
> 
> `config.yml`
> 
> * Missing property "name"
> * Missing property "description"
> * Missing property "body"
> * Property blank_issues_enabled is not allowed
> * Property contact_links is not allowed
> 
> `other.yml`
> 
> * String is shorter than the minimum length of 1 (referencing the empty string in the property `labels`)
> 
> If you want to try to "fix" these warning, feel free ... but like I said, everything seems to be working to me!

thanks! I had looked for YAML extensions earlier and couldn't find a good one, but I had taken a look at that one and didn't install it b/c of the reviews:

https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml&ssr=false#review-details

more specifically:

https://arc.net/l/quote/efazpldm (hopefully this shared quote works)

So I wonder if the errors are false positives!

Thanks for h/u and will see if I can repro.

**Pull request merged**
