### PR TITLE
Fix map search bug

### PR DESCRIPTION
**Pull request by javtran**
- Included search API to pull metrics to match our schema change
- Now able to search and switch between map and list view perfectly

### CODE REVIEW

**Comment by nickvisut** [comment]
ltgm!

**Comment by nickvisut** [comment]
was there an error being thrown w/out the metrics, btw?

**Review by nickvisut — COMMENTED** [review]
looks straightforward enough to me, although I am not familiar w/what the original issue is, so I'm unsure how to fully test it

**Review by BeeSeeWhy — APPROVED** [review]
looks good

**Pull request merged**
