### PR TITLE
Fix/mobile map height revamp

### PR DESCRIPTION
**Pull request by nickvisut**
makes progress on #99 by:
- fixing mobile map view height to be constrained to viewport height
- shows mobile map's school card
- allow mobile map's school card to be dismissed via close X icon and touching anywhere outside of the card (will likely follow this up in next PR); this persists until reload (including getting rid of "Select a school")
- add placeholder links for /profile

~~Split into two PRs~~Consolidated into one PR instead.

Completes https://github.com/sfbrigade/support-sfusd/issues/99.

### CODE REVIEW

**Review by BeeSeeWhy — CHANGES_REQUESTED** [review]
-It looks like the Map Card on desktop is no longer centered in it's div 
-it looks like you need to pull main and go through merge conflicts

**Comment by nickvisut** [comment]
> -It looks like the Map Card on desktop is no longer centered in it's div -it looks like you need to pull main and go through merge conflicts

just noticed that myself while talking to Jackson. will address and see what's up.

**Comment by nickvisut** [comment]
> -It looks like the Map Card on desktop is no longer centered in it's div -it looks like you need to pull main and go through merge conflicts

OK, both of these issues ought to be fixed now, @BeeSeeWhy. Thanks for the careful eye.

**Review by BeeSeeWhy — APPROVED** [review]
looks good.

**Pull request merged**
