### PR TITLE
[Closes #57, #58, #23] Prisma Integration 

### LINKED ISSUE #57: setting up postgres with Vercel

### PR DESCRIPTION
**Pull request by rooiss**
- Setup Postgres under the storage tab on the vercel page
- updated env file with variables for connecting prisma to vercel postgres
- created seed script for prisma to seed postgres with current school data
- updated `Schools` model in the schema file
- removed `setSelectedSchools` from props in `MapList` component
- added `getStaticProps()` to query prisma for all schools
- passed in props from `getStaticProps` into `Map` page and `Map` children components `MapList` and `Map`

### CODE REVIEW

**Review by BeeSeeWhy — CHANGES_REQUESTED** [review]
It looks like it failed in some of the vercel checks

**Comment by rooiss** [comment]
> It looks like it failed in some of the vercel checks

@BeeSeeWhy just updated so it passes now

**Review by mvyenielo — COMMENTED** [review]
Everything looks good to me as far as Prisma set up and Postgres/Vercel. I logged in to Vercel to check it out. 

For now, I would say approve, but I know there are some unanswered questions regarding the shape of the other models for the school profile and associated metrics/programs. Once we figure those out, we may have to refactor the School model, as well as how data is accessed in the various components, but we can cross that bridge when we get there.

**Review by mvyenielo — APPROVED** [review]
approving (see previous comment)

**Review by javtran — CHANGES_REQUESTED** [review]
The prisma works. I think we should edit our Readme to add some instructions to set up the db, postgresql, what commands to run, env, etc. anything related to DB. We should also consider adding a env example so it helps. 

Otherwise, it's working as expected :)

**Review by BeeSeeWhy — CHANGES_REQUESTED** [review]
Screenshot 2024-03-11 at 9 13 44 PM
I'm getting this error when I try and run the site

**Review by BeeSeeWhy — CHANGES_REQUESTED** [review]
never mind...I forgot to add to the .env file...I think we should update notion for .env file additions....or read me

**Comment by rooiss** [comment]
@javtran @BeeSeeWhy I updated our readme to include
- how we make changes to our existing models in the schema
- how to seed the database
let me know what else I can include or if this is sufficient to start

**Pull request merged**
