### PR TITLE
Fix/mapbox marker a11y

### PR DESCRIPTION
**Pull request by nickvisut**
Addresses #186.

This PR changes map markers from `div` to `button` for a11y.

This PR also sorts map markers (only on load) by latitude, and then longitude to allow for more intuitive keyboard tabbing. It leaves out logic for equator/prime meridian b/c we are only dealing with SF Bay Area.

Event listeners are added to allow for marker popups to properly be dismissed while using keyboard.

Note also that clicking a marker w/the mouse (using "space" or "enter") will also make it the active/focused element now so that keyboard navigation will start from it.

I may follow this up with the data being sorted in advance (in the seed file) as per @BeeSeeWhy's suggestion and a way to insert new data in same sorted order. Will need to learn Prisma etc first.

---

UPDATE: 8/1/2024

Also:
- enables zoom buttons
- disables rotate and pitch
- enables keyboard shortcuts (zoompan, etc)

### CODE REVIEW

**Comment by mattgianni** [comment]
Looks great to me generally. Two observations that may not be intended (observed using Chrome desktop):

- the map itself is a tab selectable item.
- the Golden Gate Bridge is also a tab selectable item on the map. We probably don't want it selectable (the Bay Bridge is not selectable), and if we do, it's out of order.

**Comment by nickvisut** [comment]
> Looks great to me generally. Two observations that may not be intended (observed using Chrome desktop):
> 
> * the map itself is a tab selectable item.
> * the Golden Gate Bridge is also a tab selectable item on the map. We probably don't want it selectable (the Bay Bridge is not selectable), and if we do, it's out of order.

Great catches, thank you. I changed the GG bridge to a div and enabled keyboard controls to the map itself so that it makes sense as a focusable item.

**Comment by nickvisut** [comment]
This is ready for review again, @mattgianni @BeeSeeWhy

**Comment by javtran** [comment]
After you space/enter a marker from using tab, are you able to space/enter again to say activate the event to navigate to the selected school profile website? @nickvisut

**Comment by nickvisut** [comment]
> After you space/enter a marker from using tab, are you able to space/enter again to navigate to the selected school profile website? @nickvisut
> 
> Or this thought just being over the top?

good Q. let me look into it.

nah, def not over the top bc we are working on general a11y and keyboard usability.

**Comment by nickvisut** [comment]
> After you space/enter a marker from using tab, are you able to space/enter again to navigate to the selected school profile website? @nickvisut
> 
> Or this thought just being over the top?

hmm looks like not. would you expect to be able to?

I *could* change focus to the Learn more button after Space/Enter, but then that would interrupt navigating the map, so I am uncertain how to satisfy both workflows. Open to suggestions.

Perhaps I can look more closely into how accessibility trees work ...

**Review by mattgianni — APPROVED** [review]
Love it.

**Comment by nickvisut** [comment]
Will make additional modifications in a follow-up PR.

**Pull request merged**
